[Indigo] cleanup urdfdom compatibility (cherry-picking #27)
moveit/srdfdom pull request #30
Opened 2017-01-31 05:22 UTC by 130s

Just noticed that https://github.com/ros/robot_model/pull/160, which https://github.com/ros-planning/srdfdom/pull/27 relies on, is backported to Indigo. So I thought https://github.com/ros-planning/srdfdom/pull/27 can also be ported back to Indigo.
Please review @v4hn @rhaschke

2017-01-31 13:44 UTC, v4hn commented
You're right, we should be able to backport this. +1
The change has been picked and was released 27 days ago, but testing failed.
Any idea why?

2017-01-31 20:20 UTC, 130s commented
Looks like `typedef` added in https://github.com/ros-planning/srdfdom/pull/18 is still necessary for IJ. Now tests passed.

2017-01-31 20:28 UTC, v4hn commented
ok, but if that is the case (right now I don't see why) then the remaining part of this pull-request reduces to adding a dependency on the "urdf" package. We don't need that dependency though! The idea was to add it and rely on that package to provide the typedefs.

2017-01-31 21:11 UTC, 130s commented
Makes sense, then I kind of found a cause of the issue but am not sure how it should be tackled.

`LinkConstSharedPtr` is called [here](https://github.com/130s/srdfdom/blob/ceccd59a9b25b290a2e0af54ef498d1b3aff6607/src/model.cpp#L182) but without `typedef`ing, it's not available.

In `robot_model`, LinkConstSharedPtr was [added in Kinetic](https://github.com/ros/robot_model/pull/144/files#diff-28ff23e8d9c8461a32d77008c1d85734R547), but [not in Indigo](https://github.com/ros/robot_model/blob/cca530eb545d8b13503dfa853367c7d078667434/collada_urdf/src/collada_urdf.cpp#L541).

2017-02-01 18:51 UTC, v4hn commented
Hm, yes. The pull-request you found is not merged into indigo. I think it should be - to ease the transition indigo->kinetic.
I don't see why this is important to back-port #27 into indigo though.

@130s could you please change this pull-request back to a cherry-pick of #27?
Without the parts you removed it does not make sense to discuss it and currently there is not even an error message to look at.

@jspricke It would be great if you could have a look.

2017-02-03 16:20 UTC, 130s commented
> change this pull-request back to a cherry-pick of #27?

Done.

2017-02-04 17:47 UTC, v4hn requested changes
Sorry, seems like I mixed up a few things when I looked at this before.
Except for the compile flag, this looks good to me.

2017-02-04 17:47 UTC, v4hn commented on CMakeLists.txt
> +
indigo should not be compiled with c++11, right?

2017-02-06 15:47 UTC, v4hn approved these changes

2017-02-06 15:48 UTC, merged