Sync noetic-devel -> ros2
moveit/srdfdom pull request #70
Opened 2020-10-12 18:04 UTC by henningkayser

2020-10-12 18:05 UTC, henningkayser commented on src/model.cpp
> +  for (XMLElement* c_xml = robot_xml->FirstChildElement("passive_joint"); c_xml; c_xml = c_xml->NextSiblingElement("pas"
This format looks weird, will fix it for noetic

2020-10-12 18:11 UTC, henningkayser commented on src/model.cpp
> +  for (XMLElement* c_xml = robot_xml->FirstChildElement("passive_joint"); c_xml; c_xml = c_xml->NextSiblingElement("pas"
#71

2020-10-13 11:44 UTC, JafarAbdi approved these changes

2020-10-13 15:53 UTC, rhaschke requested changes
The sync missed the latest ros2 commit and there are missing some changes from noetic-devel.
I'm looking into that right now.

2020-10-13 16:07 UTC, henningkayser commented
> The sync missed the latest ros2 commit and there are missing some changes from noetic-devel.
> I'm looking into that right now.

@rhaschke I see, the merge was applied to PickNikRobotics:ros2 (no issue to fix that if you didn't already do so). What's missing from noetic-devel? It includes the latest `noetic-devel` head

2020-10-13 16:11 UTC, henningkayser commented
ed8ce19 should be removed before merging

2020-10-13 16:14 UTC, rhaschke commented
You essentially dropped https://github.com/ros-planning/srdfdom/pull/70/commits/4ccc89e8a783a035316ee5cdfb99418e7e407ce1 while merging. Looks like `ament` doesn't provide a mechanism to read the version from `package.xml`? At least in MoveIt2's main repo you hard-coded the version information:
https://github.com/ros-planning/moveit2/blob/6c80d778d82ad8a283be37bf4909008ece2c93b0/moveit_core/CMakeLists.txt#L2

2020-10-13 16:47 UTC, rhaschke commented
Closing in favor of more complete #73.

2020-10-13 16:47 UTC, closed without merging